# Generated by Django 6.0.6 on 2026-07-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(default='Action', max_length=100),
        ),
    ]
