# Generated by Django 6.0.6 on 2026-07-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehub', '0002_alter_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=8.0, max_digits=2),
        ),
    ]
