# Generated by Django 6.0.6 on 2026-07-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehub', '0003_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(default='2h 00m', max_length=20),
        ),
    ]
