# Generated by Django 6.0.6 on 2026-07-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehub', '0004_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='quality',
            field=models.CharField(default='1080p', max_length=20),
        ),
    ]
